/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starry-night-8776eb46f8d549069eab1e123c913e8e
Title: Starry Night
*/

import { useAnimations, useGLTF, useTexture } from "@react-three/drei";
import { useEffect, useRef } from "react";

const StarryNight = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/starry_night.glb");
  const { actions } = useAnimations(animations, group);
  const texture = useTexture("/textures/diff.jpg");

  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => action.play());
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Plane_1" scale={24.03741837}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.002"]}
                >
                  <meshBasicMaterial map={texture} />
                </mesh>
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials["Material.002"]}
                >
                  <meshBasicMaterial map={texture} />
                </mesh>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.002"]}
                >
                  <meshBasicMaterial map={texture} />
                </mesh>
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials["Material.002"]}
                >
                  <meshBasicMaterial map={texture} />
                </mesh>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.002"]}
                >
                  <meshBasicMaterial map={texture} />
                </mesh>
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials["Material.002"]}
                >
                  <meshBasicMaterial map={texture} />
                </mesh>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.002"]}
                >
                  <meshBasicMaterial map={texture} />
                </mesh>
                <group
                  name="Plane001_0"
                  position={[0.0341937, -0.0253247, -0.05461639]}
                  rotation={[0, 0.52805167, 0]}
                  scale={0.0416018}
                >
                  <mesh
                    name="Object_12"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials.Material}
                  >
                    <meshBasicMaterial map={texture} />
                  </mesh>
                  <mesh
                    name="Object_13"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.Material}
                  >
                    <meshBasicMaterial map={texture} />
                  </mesh>
                  <mesh
                    name="Object_14"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.Material}
                  >
                    <meshBasicMaterial map={texture} />
                  </mesh>
                  <mesh
                    name="Object_15"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials.Material}
                  >
                    <meshBasicMaterial map={texture} />
                  </mesh>
                </group>
              </group>
              <group
                name="Sphere_2"
                position={[0.0000064, 0.00001092, -0.00000906]}
                scale={[-90.64975739, -90.64976501, -90.64975739]}
              >
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere001_5" scale={39.45849991}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="Cube_6"
                position={[0, -1.03748369, 0]}
                scale={0.01059078}
              >
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.007"]}
                />
              </group>
              <group
                name="Cylinder_7"
                position={[0, 48.96604156, -6.49099636]}
                scale={0}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials["Material.008"]}
                />
              </group>
              <group
                name="Cylinder001_9"
                position={[22.31953621, 48.96604156, -6.54536867]}
                scale={0}
              >
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials["Material.008"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/starry_night.glb");

export default StarryNight;
